from transformers import pipeline
import torch

model_id = "openai/gpt-oss-20b"

pipe = pipeline(
    "text-generation",
    model=model_id,
    torch_dtype="auto",
    device_map="auto",
)

def create_prompt(h1, h2, h3):
    prompt = f'''Perform error correction based on the top3 outputs generated by an Automatic Speech Recognition (ASR) system. The ASR hypotheses are listed in order of their ASR posterior score. Please provide the corrected top1 ASR transcription of the given utterance only.  Do not add any explanations or other words. 

        Here are a few in-context examples: 

        Example 1:
        <hypothesis1>जी नमस्ते जी बोलिए</hypothesis1> 
        <hypothesis2>जी नमस्ते जी बुलिये</hypothesis2> 
        <hypothesis3>जी नमस्ते जी बोल्गे</hypothesis3> 

        Your output: जी नमस्ते जी बोलिए

        Example 2:
        <hypothesis1>जी</hypothesis1> 
        <hypothesis2>वे</hypothesis2> 
        <hypothesis3>धन्यवाद</hypothesis3>

        Your output: जी

        Example 3:
        <hypothesis1>अगर आपका बच्चा चला जाएगा तो फिर उनका लॉस हो जाएगा ना ब अगर हम आपको छुट्टी दे भी रहे हैं तो मैम आपका चार्ज ज़्यादा लगेगा</hypothesis1> 
        <hypothesis2>अगर आपका बच्चा चला जाएगा तो फिर उनका लॉस हो जाएगा न  अगर हम आपको छुट्टी देभी रहै तो महम आपका चार ज्यादा लगेगा</hypothesis2> 
        <hypothesis3>अगर आपका बच्चा चला जायेगा तो फिर उनका लॉस हो जायेगा न बस अगर हम आपको छुट्टी दे भी रहे तो माम आपका चार्ज ज्यादा लगेगा</hypothesis3> 

        Your output: अगर आपका बच्चा चला जाएगा तो फिर उनका लॉस हो जाएगा ना बट अगर हम आपको छुट्टी दे भी रहे हैं तो मैम आपका साल ज्यादा लगेगा

        Example 4:
        <hypothesis1>जी बिल्कुल</hypothesis1> 
        <hypothesis2>दजी बुलकू</hypothesis2> 
        <hypothesis3>तुझी भूल कर</hypothesis3>

        Your output: जी बिल्कुल

        Example 5:
        <hypothesis1>जी जी वैसे दो ढाई जन लग रहा है</hypothesis1> 
        <hypothesis2>तजी जी वैसे दो ढाइडर लग रहा है</hypothesis2> 
        <hypothesis3>जीजी वैसे दो ढाई जल लग रहा </hypothesis3>
  
        Your output: जी जी वैसे दो ढाई हजार लग रहा है

        Example 6:
        <hypothesis1>ढाई हजार लग रहा है तो ठीक है हम चार्ज तो नहीं कम कर सकते हैं आप बीच में भी बीच में जा ही रही हैं और बच्चे का लॉस भी होगा</hypothesis1> 
        <hypothesis2>डाइगर लग रहा है तो ठीक है हम चाज तो नहीं कम कर सकते हैं आप अबी इस में भी भीच में जाही नहीं हैं और बच्चे का लॉस भी होगा</hypothesis2> 
        <hypothesis3>ढाई अज़र लग रहा है तू थी एक है चार्ज तो नहीं कम कर सकते है आपको बीच में भी बीच में जाए ही नहीं है और बच्चे का लॉस भी होगा</hypothesis3>

        Your output: ढाई हजार लग रहा है दो तो ठीक है हम चार्ज तो नहीं कम कर सकते हैं आप बीच में भी बीच में जा ही रही हैं और बच्चे का लॉस भी होगा 

        Example 7:
        <hypothesis1>और आप तो ये भी बोल रहे हो कि मतलब बच्चा है तो अकेले नहीं छोड़ेंगे आपकी भी बात सही है किसी बच्चे को तो भई माँ के बिना तो आप जा रही हो तो आपकी तो चिंता बनी ही रहेगी सही बात है</hypothesis1> 
        <hypothesis2>और आपतो यदि बोल रहे हो कि मलबच्चा है तो अकेले नहीं छोड़ेंगे आपकी भी बात सही है किसी बच्चे को तो बई माँ के बिना तो आप जा रहे है तो आपकी तो चिंता बने ही रहेगी सही बात है</hypothesis2> 
        <hypothesis3>और आप तो यदि बोल रहे हो की मतलब बच्चा है तो अकेले नहीं छोड़ेंगे आपकी भी बात सही है किसी बच्चे को तो माँ के बिना तो आप जा रहे हैं तो आपकी तो चिंता बनी ही रहेगी सही बात है</hypothesis3>

        Your output: और आप तो ये भी बोल रहे हो कि मतलब बच्चा है तो अकेले नहीं छोडेंगे आपकी भी बात सही हैं किसी बच्चे को तो भाई माँ के बिना तो आप जा रही हैं सो आपकी तो चिंता बनी ही रहेगी सही बात है

        Example 8:
        <hypothesis1>बट आप क रही हैं तो ठीक है हम आपको छुट्टी दे दे रहे हैं बट जो भी इनकी तैयारी है आप वहाँ पे कराते रहिएगा क्योंकि भई बच्चे</hypothesis1> 
        <hypothesis2>बस आप कह रहे हैं तो ठीक ह हम आपको छुट्ठी दे दे रहा हैं जो भी इनकी तैयारी है आप वहां पि खराते रहिएगा क्योंकि भी बच्चे </hypothesis2> 
        <hypothesis3>बस आप कह रही है तो ठीक है हम आपको छुट्टी दे दे रहा है जो भी इनकी तैयारी है आप वहाँ ऐसी करते रहियेगा क्यूँकी भाई बच्चे</hypothesis3>

        Your output: बट आप क केह रही हैं तो ठीक है हम आपको छुट्टी दे दे रहे हैं बट जो भी इनकी तैयारी है आप वहाँ पे कराते रहिएगा क्योंकि भाई बच्चे

        Example 9:
        <hypothesis1>जी बिल्कुल बिल्कुल ठीक</hypothesis1> 
        <hypothesis2>जी बिल्कुल बिल्कुल ठीक </hypothesis2> 
        <hypothesis3>जी बिल्कुल बिल्कुल ठीक</hypothesis3>

        Your output: जी बिलकुल बिलकुल ठीक

        Example 10:
        <hypothesis1>जी तो कितने दिन की चाहिए डेस बता दीजिए</hypothesis1> 
        <hypothesis2>छी तो कितने दिन की चाहिए डेर बता दीजिए</hypothesis2> 
        <hypothesis3>जी तो कितने दिन के चाहिए ढेर बता दीजिए</hypothesis3>

        Your output: जी तो कितने दिन की चाहिए डे बता दीजिए

        Example 11:
        <hypothesis1>ओके ऐसे ही आपको जाना कौन सी जगह पर है</hypothesis1> 
        <hypothesis2>केऐसे आपको जाना कौंस जगह पर</hypothesis2> 
        <hypothesis3>एक्सपेनेम ऐसे आपको जाना कौन सी जगह पर है</hypothesis3> 

        Your output: ओके ऐसे आपको जाना कौनसी जगह पर है

        Example 12:
        <hypothesis1>तो ताजमहल घुमाने जा रही हैं बच्चे को</hypothesis1> 
        <hypothesis2>तो ताडमल गमाने जारहे बच्चे को</hypothesis2> 
        <hypothesis3>तो साजना घुमाने जा रही है बच्चे को</hypothesis3> 

        Your output: तो ताजमहल घुमाने जा रही हैं बच्चे को

        Example 13:
        <hypothesis1>ओके मैम ठींक है</hypothesis1> 
        <hypothesis2>ओके मैम इनका</hypothesis2> 
        <hypothesis3>ओके माम थाने क्या</hypothesis3

        Please feel free to refer to these examples. Do not output any placeholder tokens or angle‑bracketed markers (e.g. <output>).
        Provide only the corrected transcription, with no extra words, symbols, or tags. Please start: 
        <hypothesis1>{h1}</hypothesis1>
        <hypothesis2>{h2}</hypothesis2>
        <hypothesis3>{h3}</hypothesis3>

>'''

    return prompt

query_prompt = create_prompt("किम ने उन्नीस सौ तिरानवे में फ़िल्म उद्योग से संन्यास ले लिया उनकी आखिरी फ़िल्म में प्रतिकार हनीिमून बलवान मुस्कुराहट और बुलन में अतिथि भूमिकाएँ थीं", "कीम ने <unk><unk><unk><unk> में फिल्म उद्योग से संन्यास ले लिया उनकी आखिरी फिल्म में प्रतिकार हनिमून बलवान मुस्कराहट और बुलन में अतिथि भूमिकाएं थीं", "किम ने एक हज़ार नौ सौ तिरानवे में फ़िल्म उद्योग से संन्यास ले लिया उनकी आख़िरी फ़िल्में प्रतिकार हनीमून बलवान मुस्कार्हट और बुलंद में अतिथि भूमिकाएं थीं")

messages = [
    {"role": "user", "content": query_prompt},
]

outputs = pipe(
    messages,
    max_new_tokens=256,
)

raw = outputs[0]["generated_text"][-1]["content"]

# If the model outputs markers like "assistantfinal"
if "assistantfinal" in raw:
    #Split and take everything after the marker
    final_answer = raw.split("assistantfinal", 1)[1].strip()
else:
    #If no marker, just take the raw text
    final_answer = raw.strip()

print(raw)

def create_oov_prompt(h1):
    prompt=f'''Please modify the given transcript, which contain out of vocabulary words, to be written in the correct format. Use the examples below as a reference on how to modify the transcript.

        Here are a few Out of Vocabulary (OOV) in-context examples which contain numbers:

        OOV Example 1:
        <hypothesis1>अब खर्चा के हिसाब से तोग लगभग लगभग तीन तीन से साढ़े तीन चार हजार के लगभग लग जाएगा भाई क्योंकि उसमें उपकरण भी उपयोग होंगे इस हिसाब से</hypothesis1>
        <hypothesis2>अब खर्चा के साबसे तो लगभग लगभग तीन तीन से साढ़े तीनचार हजार के लगभग लग झाए रवाई क्योंकि उसमें उपकरण भी उपयोग होएंगे ऐसे साब से</hypothesis2>
        <hypothesis3>जी जी वैसे दो ढाई जल लग रहा है</hypothesis3>

        Your output: जी जी वैसे दो ढाई हजार लग रहा है', 'ढाई हजार लग रहा है दो तो ठीक है हम चार्ज तो नहीं कम कर सकते हैं आप बीच में भी बीच में जा ही रही हैं और बच्चे का लॉस भी होगा

        OOV Example 2:
        <hypothesis1>मैंने मित्रा पर बोस कवाइड कम्पोस्ट पैंतालीस के लिए रुपये तेईस सौ छः का आऑर्डर दिया है क्या आप दो बार जाँच कर सकते हैं कि सब कुछ सही है या नहीं</hypothesis1>
        <hypothesis2>मैंने मित्रा परबोसक्वाइडकंपोस्ट <unk><unk> के लिए रुपये <unk><unk><unk> का ऑर्डर दिया है क्या आप दो बार जाँच कर सकते हैं कि सबकुछ सही है या नहीं</hypothesis2>
        <hypothesis3>नायजर लग रहा है तो ठीक है हम चार्ज तो नहीं कम कर सकते हैं आपको बीच में भी बीच में जाए ही नहीं हैं और बच्चे का लॉस भी होगा</hypothesis3>

        Your output: कल शाम को ट्रैफिक में हम लगभग तीन सौ पचास मीटर तक गाड़ी धीरे-धीरे चली थी असल में रात आठ बजे तक जाम था

        OOV Example 3:
        <hypothesis1>हाँ मैंने फ़ोन एक बार किया था आप कोई फाम नहीं है और एक मेरे को साइकिल चाहिए थी</hypothesis1>
        <hypothesis2> मैंने फूनी को किया था कुर फाम औरएक मेन कुस साइकिल ची थी</hypothesis2>
        <hypothesis3>क्यूँकी वो आप लोग हमारे ही ऊपर छोड़कर जाते है और बच्चा पाँच घंटा छेह घंटा रहता है तो हमारी ही बनती है की हम बच्चों कैसे कैसे कितना हद तक सिखा दे की मतलब आप बहुत</hypothesis3>

        Your output: मुझे पता करना है कि उस मेडिकल कॉलेज में शैक्षणिक सत्र दो हज़ार पंद्रह से दो हज़ार बीस के बीच कितना प्रतिष्ठित माना जाता था

        OOV Example 4:
        <hypothesis1>अच्छाना हीतना मेरे को सात आठ हज़ार तक अगर कोई है तो बता बता दीजिए</hypothesis1>
        <hypothesis2>सुनना ही तुरानत वी मर को सातार हजार तककर कोई है तो बता तो बता दी जी रहे</hypothesis2>
        <hypothesis3>अब भी बच्चों को प्रेरित करोगी की हाँ हमारा बच्चा वहाँ पढ़ रहा हैं आप अपने बच्चों को वहाँ डाल लीजिये क्यूँकी मेरा बच्चा वहीं पढ़ के इतने अच्छे ट्रांसफ्री हुआ हैं फिर जो भी वेकेशन हैं फशन हैं फिफ्टीन अगस्त हुआ हैं ट्वेंटी शिव जनवरी होगी इसके जो डांस होता हैं आपको पता ही हैं</hypothesis3>


        Your output: क्या आपकी कंपनी पिछले पाँच वर्ष में कम से कम बारह सौ नए प्लांटर्स लॉन्च कर चुकी है

        OOV Example 5:
        <hypothesis1>व तो ठीक है ना नहीं है तो हमको भेज दीजिए यही वाला हम देख के बताते हैं ठीक है हमको जल्दी भेज दीजिए</hypothesis1>
        <hypothesis2>होें तो ठीक है न नहीं है तो हमको भेज दीजिया और आम देखकर बतादे ै ठीक ह अमकु जल्दी भेज दीजिए</hypothesis2>
        <hypothesis3>यही चार्ज पाँच सौ रुपये दिन है</hypothesis3>

        Your output: मैरे मित्र ने कहा कि उस इलाके में सालाना करीब तीन लाख पचास हजार पर्यटक आते हैं आप यह आंकड़ा देख सकते हैं  

        Please feel free to refer to these examples. Do not output any placeholder tokens or angle‑bracketed markers (e.g. <output>).
        Provide only provide the corrected transcript, with no extra words, symbols, or tags. Please start:

        <hypothesis1>{h1}</hypothesis1>

 '''

    return prompt



oov_prompt = create_oov_prompt(raw)

messages = [
    {"role": "user", "content": oov_prompt},
]

outputs = pipe(
    messages,
    max_new_tokens=256,
)

oov_raw = outputs[0]["generated_text"][-1]["content"]

# If the model outputs markers like "assistantfinal"
if "assistantfinal" in oov_raw:
    #Split and take everything after the marker
    final_answer = raw.split("assistantfinal", 1)[1].strip()
else:
    #If no marker, just take the raw text
    final_answer = raw.strip()

print(oov_raw)
