import getpass
import os
import bs4
from langchain import hub
from langchain_community.document_loaders import WebBaseLoader
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langgraph.graph import START, StateGraph
from typing_extensions import List, TypedDict
from langchain.chat_models import init_chat_model
from langchain_openai import OpenAIEmbeddings
from langchain_core.vectorstores import InMemoryVectorStore
from datasets import load_dataset
from openai import OpenAI


ds = iter(load_dataset("ai4bharat/IndicVoices", "hindi", split="train", streaming=True))
texts = []
for _ in range(1000):
    sample = next(ds)
    texts.append(sample['verbatim'])

os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGSMITH_API_KEY"] = "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"

if not os.environ.get("OPENAI_API_KEY"):
  os.environ["OPENAI_API_KEY"] = "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"
API_KEY = "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"


client = OpenAI()

embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

vector_store = InMemoryVectorStore(embeddings)

docs = [Document(page_content=text, metadata={"id": i}) for i, text in enumerate(texts)]

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
all_splits = text_splitter.split_documents(docs)

# Index chunks
_ = vector_store.add_documents(documents=all_splits)

# Define prompt for question-answering

# Define state for application
class State(TypedDict):
    h1: str
    h2: str
    h3: str
    context: List[Document]
    answer: str


# Define application steps
def retrieve(state: State):
    retrieved_docs = vector_store.similarity_search(state["h1"])
    return {"context": retrieved_docs}


def generate(state: State):
    docs_content = "\n\n".join(doc.page_content for doc in state["context"])
    prompt = f'''Perform error correction based on the top3 outputs generated by an Automatic Speech Recognition (ASR) system. The ASR hypotheses are listed in order of their ASR posterior score. Please provide the corrected top1 ASR transcription of the given utterance only.  Do not add any explanations or other words. 

        Here are a few in-context examples: 

        Example 1:
        <hypothesis1>जी नमस्ते जी बोलिए</hypothesis1> 
        <hypothesis2>क प</hypothesis2> 
        <hypothesis3>जी नमस्ते जी बोल्गे</hypothesis3> 

        Your output: जी नमस्ते जी बोलिए

        Example 2:
        <hypothesis1>जी</hypothesis1> 
        <hypothesis2></hypothesis2> 
        <hypothesis3>धन्यवाद</hypothesis3>

        Your output: जी

        Example 3:
        <hypothesis1>अगर आपका बच्चा चला जाएगा तो फिर उनका लॉस हो जाएगा ना ब अगर हम आपको छुट्टी दे भी रहे हैं तो मैम आपका चार्ज ज़्यादा लगेगा</hypothesis1> 
        <hypothesis2></hypothesis2> 
        <hypothesis3>अगर आपका बच्चा चला जायेगा तो फिर उनका लॉस हो जायेगा न बस अगर हम आपको छुट्टी दे भी रहे तो माम आपका चार्ज ज्यादा लगेगा</hypothesis3> 

        Your output: अगर आपका बच्चा चला जाएगा तो फिर उनका लॉस हो जाएगा ना बट अगर हम आपको छुट्टी दे भी रहे हैं तो मैम आपका साल ज्यादा लगेगा

        Example 4:
        <hypothesis1>जी बिल्कुल</hypothesis1> 
        <hypothesis2></hypothesis2> 
        <hypothesis3>तुझी भूल कर</hypothesis3>

        Your output: जी बिल्कुल

        Example 5:
        <hypothesis1>जी जी वैसे दो ढाई जन लग रहा है</hypothesis1> 
        <hypothesis2>ा का क</hypothesis2> 
        <hypothesis3>जीजी वैसे दो ढाई जल लग रहा </hypothesis3>
  
        Your output: जी जी वैसे दो ढाई हजार लग रहा है

        Example 6:
        <hypothesis1>ढाई हजार लग रहा है तो ठीक है हम चार्ज तो नहीं कम कर सकते हैं आप बीच में भी बीच में जा ही रही हैं और बच्चे का लॉस भी होगा</hypothesis1> 
        <hypothesis2>क क क र</hypothesis2> 
        <hypothesis3>ढाई अज़र लग रहा है तू थी एक है चार्ज तो नहीं कम कर सकते है आपको बीच में भी बीच में जाए ही नहीं है और बच्चे का लॉस भी होगा</hypothesis3>

        Your output: ढाई हजार लग रहा है दो तो ठीक है हम चार्ज तो नहीं कम कर सकते हैं आप बीच में भी बीच में जा ही रही हैं और बच्चे का लॉस भी होगा 

        Example 7:
        <hypothesis1>और आप तो ये भी बोल रहे हो कि मतलब बच्चा है तो अकेले नहीं छोड़ेंगे आपकी भी बात सही है किसी बच्चे को तो भई माँ के बिना तो आप जा रही हो तो आपकी तो चिंता बनी ही रहेगी सही बात है</hypothesis1> 
        <hypothesis2>क क क क क</hypothesis2> 
        <hypothesis3>और आप तो यदि बोल रहे हो की मतलब बच्चा है तो अकेले नहीं छोड़ेंगे आपकी भी बात सही है किसी बच्चे को तो माँ के बिना तो आप जा रहे हैं तो आपकी तो चिंता बनी ही रहेगी सही बात है</hypothesis3>

        Your output: और आप तो ये भी बोल रहे हो कि मतलब बच्चा है तो अकेले नहीं छोडेंगे आपकी भी बात सही हैं किसी बच्चे को तो भाई माँ के बिना तो आप जा रही हैं सो आपकी तो चिंता बनी ही रहेगी सही बात है

        Example 8:
        <hypothesis1>बट आप क रही हैं तो ठीक है हम आपको छुट्टी दे दे रहे हैं बट जो भी इनकी तैयारी है आप वहाँ पे कराते रहिएगा क्योंकि भई बच्चे</hypothesis1> 
        <hypothesis2>प क पर क ा</hypothesis2> 
        <hypothesis3>बस आप कह रही है तो ठीक है हम आपको छुट्टी दे दे रहा है जो भी इनकी तैयारी है आप वहाँ ऐसी करते रहियेगा क्यूँकी भाई बच्चे</hypothesis3>

        Your output: बट आप क केह रही हैं तो ठीक है हम आपको छुट्टी दे दे रहे हैं बट जो भी इनकी तैयारी है आप वहाँ पे कराते रहिएगा क्योंकि भाई बच्चे

        Example 9:
        <hypothesis1>जी बिल्कुल बिल्कुल ठीक</hypothesis1> 
        <hypothesis2>ा र के प</hypothesis2> 
        <hypothesis3>जी बिल्कुल बिल्कुल ठीक</hypothesis3>

        Your output: जी बिलकुल बिलकुल ठीक

        Example 10:
        <hypothesis1>जी तो कितने दिन की चाहिए डेस बता दीजिए</hypothesis1> 
        <hypothesis2>ा क क क</hypothesis2> 
        <hypothesis3>जी तो कितने दिन के चाहिए ढेर बता दीजिए</hypothesis3>

        Your output: जी तो कितने दिन की चाहिए डे बता दीजिए

        Example 11:
        <hypothesis1>ओके ऐसे ही आपको जाना कौन सी जगह पर है</hypothesis1> 
        <hypothesis2>क क का क</hypothesis2> 
        <hypothesis3>एक्सपेनेम ऐसे आपको जाना कौन सी जगह पर है</hypothesis3> 

        Your output: ओके ऐसे आपको जाना कौनसी जगह पर है

        Example 12:
        <hypothesis1>तो ताजमहल घुमाने जा रही हैं बच्चे को</hypothesis1> 
        <hypothesis2>ा</hypothesis2> 
        <hypothesis3>तो साजना घुमाने जा रही है बच्चे को</hypothesis3> 

        Your output: तो ताजमहल घुमाने जा रही हैं बच्चे को

        Example 13:
        <hypothesis1>ओके मैम ठींक है</hypothesis1> 
        <hypothesis2>ा</hypothesis2> 
        <hypothesis3>ओके माम थाने क्या</hypothesis3>

        Your output: ओके मैम ठीक है
        

        Please feel free to refer to this example. Do not output any placeholder tokens or angle‑bracketed markers (e.g. <output>).
        Provide only the corrected transcription, with no extra words, symbols, or tags.
         
        Here are some additional context/phrases that are semantically similar to the corrected transcript that you could refer to: {docs_content}

        Please start: 
        <hypothesis1>{state["h1"]}</hypothesis1> 
        <hypothesis2>{state["h2"]}</hypothesis2> 
        <hypothesis3>{state["h3"]}</hypothesis3>
    '''
    print("Context", docs_content)
    response = client.chat.completions.create(
        model="gpt-4.1",
        messages=[{"role":"user","content":prompt}],
        temperature=0,
        # top_p=1,
        # max_tokens=4096,
    )
    return {"answer": response.choices[0].message.content.strip()}


# Compile application and test
graph_builder = StateGraph(State).add_sequence([retrieve, generate])
graph_builder.add_edge(START, "retrieve")
graph = graph_builder.compile()

response = graph.invoke({"h1": "किम ने उन्नीस सौ तिरनवे में फ़िल्म उद्योग से संन्यास ले लिया उनकी आखिरी फिल्में प्रतिकार हनीमून बलवान मुस्कहट और बुलंद में अतिथि भूमिकाएँ थीं", "h2": "किम ने एक हज़ार नौ सौ तिरानवे में फ़िल्म उद्योग से संन्यास ले लिया उनकी आख़िरी फ़िल्में प्रतिकार हनीमून बलवान मुस्कार्हट और बुलंद में अतिथि भूमिकाएं थीं", "h3": "कीम ने एक हज़ार नौ सौ तिरानवे में फिल्म उद्योग से सन्यास ले लिया उनकी आखिरी फिल्में प्रतिकार हनीिमून बलवान मुस्क्राहट और बुलन में अतिथि भूमिकाए थ"})
print(response["answer"])
